### ISSUE TITLE
Is it production ready yet?

### ISSUE THREAD

**Issue by chgz** [thinkgos/timer#5]
@thinkgos 
hi，thanks for sharing this repo.
I need it.
Is it production ready yet?

**Comment by thinkgos** [comment]
What are the questions about this repository?  
this repository currently used in the company's products.   
implementation of Kafka's Hierarchical Timing Wheels, the code is very easy, you can read it, if find any issue, pull request welcome.

**Comment by thinkgos** [comment]
@chgz  Are you in Fuzhou, which company are you in Fuzhou?

**Comment by chgz** [comment]
:simileIGG.com

**Comment by chgz** [comment]
😄   yes

**Comment by chgz** [comment]
IGG.com

**Comment by chgz** [comment]
I took a rough look， the code is very clear 👍 
IMO, there are many pointer objects. If there is a large-scale tasks, will the GC have a significant load, especially during the scanning phase?

**Comment by chgz** [comment]
ok！
I'll try this repo

**Comment by thinkgos** [comment]
@chgz personal wechat, thinkgo510
